//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleCode.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;

    public partial class Matches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matches()
        {
            this.Submissions = new HashSet<Submissions>();
            this.Problems = new HashSet<Problems>();
        }
    
        public int MatchId { get; set; }
        public int Player1Id { get; set; }
        public Nullable<int> Player2Id { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
        public string MatchStatus { get; set; }
        public Nullable<int> WinnerId { get; set; }
        public Nullable<bool> IsPractice { get; set; }
        public Nullable<bool> IsDraw { get; set; }
        public string Mode { get; set; }
        public Nullable<int> Player1Score { get; set; }
        public Nullable<int> Player2Score { get; set; }
        public Nullable<int> Player1CorrectCount { get; set; }
        public Nullable<int> Player2CorrectCount { get; set; }
        public Nullable<int> Player1Rank { get; set; }
        public Nullable<int> Player2Rank { get; set; }
        public string Language { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submissions> Submissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Problems> Problems { get; set; }

        public static implicit operator Match(Matches v)
        {
            throw new NotImplementedException();
        }
    }
}
