//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submissions
    {
        public int SubmissionId { get; set; }
        public int MatchId { get; set; }
        public int ProblemId { get; set; }
        public int UserId { get; set; }
        public string Language { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
        public string Result { get; set; }
        public Nullable<int> ExecutionTimeMs { get; set; }
        public string Output { get; set; }
        public string ErrorMessage { get; set; }
        public string HintText { get; set; }
        public string AIAnalysis { get; set; }
    
        public virtual Matches Matches { get; set; }
        public virtual Problems Problems { get; set; }
        public virtual Users Users { get; set; }
    }
}
